In [18]:
import numpy as np
import pandas as pd

In [58]:
dos_dataset=pd.read_csv('/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/DoS_dataset.csv',header=None,on_bad_lines='skip')
fuzzy_dataset=pd.read_csv('/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/Fuzzy_dataset.csv',header=None,on_bad_lines='skip')
gear_dataset=pd.read_csv('/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/gear_dataset.csv',header=None,on_bad_lines='skip')
rpm_dataset=pd.read_csv('/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/RPM_dataset.csv',header=None,on_bad_lines='skip')

/var/folders/x0/vvyylb8n1wqf9887q2q2mcwc0000gn/T/ipykernel_92712/1216182563.py:2: DtypeWarning: Columns (0: 6, 1: 9, 2: 11) have mixed types. Specify dtype option on import or set low_memory=False.
  fuzzy_dataset=pd.read_csv('/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/Fuzzy_dataset.csv',header=None,on_bad_lines='skip')
/var/folders/x0/vvyylb8n1wqf9887q2q2mcwc0000gn/T/ipykernel_92712/1216182563.py:3: DtypeWarning: Columns (0: 3, 1: 4, 2: 6, 3: 8) have mixed types. Specify dtype option on import or set low_memory=False.
  gear_dataset=pd.read_csv('/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/gear_dataset.csv',header=None,on_bad_lines='skip')

In [20]:
import pandas as pd

rows = []

file_path = "/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/normal_run_data.txt"   # Change if needed

with open(file_path, "r") as f:
    for line in f:

        line = line.strip()
        if not line:
            continue
        if not line.startswith("Timestamp:"):
            continue

        parts = line.split()

        try:
            timestamp = float(parts[1])
            can_id = int(parts[3], 16)
            rtr = int(parts[4])
            dlc = int(parts[6])
            data = parts[7:]
            data = [int(byte, 16) for byte in data]
            while len(data) < 8:
                data.append(0)
            data = data[:8]
            rows.append({
                "timestamp": timestamp,
                "can_id": can_id,
                "rtr": rtr,
                "dlc": dlc,
                "d0": data[0],
                "d1": data[1],
                "d2": data[2],
                "d3": data[3],
                "d4": data[4],
                "d5": data[5],
                "d6": data[6],
                "d7": data[7],
            })

        except Exception:
            continue

normal_dataset = pd.DataFrame(rows)

In [63]:
##save to itt
normal_dataset["label"] = 0
normal_dataset["attack_type"] = "normal"
op_loc="/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/processed/normal.csv"
normal_dataset

,timestamp,can_id,rtr,dlc,d0,d1,d2,d3,d4,d5,d6,d7,label,attack_type
0,1.479121e+09,848,0,8,5,40,132,102,109,0,0,162,0,normal
1,1.479121e+09,704,0,8,20,0,0,0,0,0,0,0,0,normal
2,1.479121e+09,1072,0,8,0,0,0,0,0,0,0,0,0,normal
3,1.479121e+09,1201,0,8,0,0,0,0,0,0,0,0,0,normal
4,1.479121e+09,497,0,8,0,0,0,0,0,0,0,0,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988866,1.479122e+09,688,0,5,172,5,12,7,127,0,0,0,0,normal
988867,1.479122e+09,790,0,8,5,56,16,12,56,40,1,122,0,normal
988868,1.479122e+09,399,0,8,254,49,0,0,0,75,0,0,0,normal
988869,1.479122e+09,608,0,8,50,56,57,48,255,147,89,28,0,normal
988870,1.479122e+09,672,0,8,32,0,117,29,1,4,221,0,0,normal

In [22]:
normal_dataset.to_csv(op_loc)

In [23]:
normal_dataset

,timestamp,can_id,rtr,dlc,d0,d1,d2,d3,d4,d5,d6,d7,label,attack_type
0,1.479121e+09,848,0,8,5,40,132,102,109,0,0,162,0,normal
1,1.479121e+09,704,0,8,20,0,0,0,0,0,0,0,0,normal
2,1.479121e+09,1072,0,8,0,0,0,0,0,0,0,0,0,normal
3,1.479121e+09,1201,0,8,0,0,0,0,0,0,0,0,0,normal
4,1.479121e+09,497,0,8,0,0,0,0,0,0,0,0,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988866,1.479122e+09,688,0,5,172,5,12,7,127,0,0,0,0,normal
988867,1.479122e+09,790,0,8,5,56,16,12,56,40,1,122,0,normal
988868,1.479122e+09,399,0,8,254,49,0,0,0,75,0,0,0,normal
988869,1.479122e+09,608,0,8,50,56,57,48,255,147,89,28,0,normal
988870,1.479122e+09,672,0,8,32,0,117,29,1,4,221,0,0,normal

In [36]:
##eda for dosss

dos_dataset.shape
dos_dataset.head()

             0     1   2   3   4   5   6   7   8   9   10 11
0  1.478198e+09  0316   8  05  21  68  09  21  21  00  6f  R
1  1.478198e+09  018f   8  fe  5b  00  00  00  3c  00  00  R
2  1.478198e+09  0260   8  19  21  22  30  08  8e  6d  3a  R
3  1.478198e+09  02a0   8  64  00  9a  1d  97  02  bd  00  R
4  1.478198e+09  0329   8  40  bb  7f  14  11  20  00  14  R

In [37]:
dos_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 3665771 entries, 0 to 3665770
Data columns (total 12 columns):
 #   Column  Dtype
---  ------  -----
 0   0       float64
 1   1       str
 2   2       int64
 3   3       str
 4   4       str
 5   5       str
 6   6       str
 7   7       str
 8   8       str
 9   9       str
 10  10      str
 11  11      str
dtypes: float64(1), int64(1), str(10)
memory usage: 335.6 MB

shape of doss is (3665770, 12)

In [42]:
dos_dataset.columns = [
    "timestamp", "can_id", "dlc", "d0",
    "d1","d2", "d3", "d4", "d5", "d6", "d7","label"
]
dos_dataset.insert(2, "rtr", 0) ##add rtr 
dos_dataset["timestamp"] = dos_dataset["timestamp"].astype(float)

In [43]:
dos_dataset['can_id']=dos_dataset['can_id'].apply(lambda x:int(str(x),16))

In [ ]:
payload_columns = ["d0","d1","d2","d3",
    "d4","d5","d6","d7"
]

for col in payload_columns:
    dos_dataset[col] = dos_dataset[col].apply(
        lambda x: int(str(x),16) ## error this wayy
  )

ValueError: invalid literal for int() with base 16: 'R'

In [46]:
for col in payload_columns:
    print(col)
    print(dos_dataset[dos_dataset[col] == "R"])

d0
Empty DataFrame
Columns: [timestamp, can_id, rtr, dlc, d0, d1, d2, d3, d4, d5, d6, d7, label]
Index: []
d1
Empty DataFrame
Columns: [timestamp, can_id, rtr, dlc, d0, d1, d2, d3, d4, d5, d6, d7, label]
Index: []
d2
            timestamp  can_id  rtr  dlc  d0  d1 d2   d3   d4   d5   d6   d7  \
36       1.478198e+09    1520    0    2   1   0  R  NaN  NaN  NaN  NaN  NaN
135      1.478198e+09    1520    0    2   1   0  R  NaN  NaN  NaN  NaN  NaN
227      1.478198e+09    1520    0    2   1   0  R  NaN  NaN  NaN  NaN  NaN
320      1.478198e+09    1520    0    2   1   0  R  NaN  NaN  NaN  NaN  NaN
412      1.478198e+09    1520    0    2   1   0  R  NaN  NaN  NaN  NaN  NaN
...               ...     ...  ...  ...  ..  .. ..  ...  ...  ...  ...  ...
3665351  1.478201e+09    1520    0    2   1   0  R  NaN  NaN  NaN  NaN  NaN
3665443  1.478201e+09    1520    0    2   1   0  R  NaN  NaN  NaN  NaN  NaN
3665536  1.478201e+09    1520    0    2   1   0  R  NaN  NaN  NaN  NaN  NaN
3665628  1.478201e+09    1520    0    2   1   0  R  NaN  NaN  NaN  NaN  NaN
3665721  1.478201e+09    1520    0    2   1   0  R  NaN  NaN  NaN  NaN  NaN

        label
36        NaN
135       NaN
227       NaN
320       NaN
412       NaN
...       ...
3665351   NaN
3665443   NaN
3665536   NaN
3665628   NaN
3665721   NaN

[31188 rows x 13 columns]
d3
Empty DataFrame
Columns: [timestamp, can_id, rtr, dlc, d0, d1, d2, d3, d4, d5, d6, d7, label]
Index: []
d4
Empty DataFrame
Columns: [timestamp, can_id, rtr, dlc, d0, d1, d2, d3, d4, d5, d6, d7, label]
Index: []
d5
Empty DataFrame
Columns: [timestamp, can_id, rtr, dlc, d0, d1, d2, d3, d4, d5, d6, d7, label]
Index: []
d6
Empty DataFrame
Columns: [timestamp, can_id, rtr, dlc, d0, d1, d2, d3, d4, d5, d6, d7, label]
Index: []
d7
Empty DataFrame
Columns: [timestamp, can_id, rtr, dlc, d0, d1, d2, d3, d4, d5, d6, d7, label]
Index: []

In [ ]:
from pathlib import Path
import pandas as pd

raw = Path("/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/DoS_dataset.csv")
PROCESSED_DIR = Path("/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

rows = []

with open(raw, "r") as file:
    for line_num, line in enumerate(file, start=1):
        line = line.strip()
        if not line:
            continue

        parts = line.split(",")

        try:

            timestamp = float(parts[0])

            can_id = int(parts[1], 16)

            dlc = int(parts[2])
            payload = parts[3:-1]
            payload = [int(byte, 16) for byte in payload]
            while len(payload) < 8:
                payload.append(0)

            payload = payload[:8]
            raw_label = parts[-1].strip()

            if raw_label == "R":
                label = 0
                attack_type = "normal"

            elif raw_label == "T":
                label = 1
                attack_type = "dos"

            else:
                continue

            rows.append({
                "timestamp": timestamp,
                "can_id": can_id,
                "rtr": 0,
                "dlc": dlc,
                "d0": payload[0],
                "d1": payload[1],
                "d2": payload[2],
                "d3": payload[3],
                "d4": payload[4],
                "d5": payload[5],
                "d6": payload[6],
                "d7": payload[7],
                "label": label,
                "attack_type": attack_type
            })

        except Exception as e:

            print(f"Skipping line {line_num}: {e}")

            continue
dos_dataset = pd.DataFrame(rows)
output_file = PROCESSED_DIR / "dos_processed.csv"
dos_dataset.to_csv(output_file, index=False)

Shape              : (3665771, 14)
Missing Values     : 0
Duplicate Rows     : 0

Label Distribution
label
0    3078250
1     587521
Name: count, dtype: int64

Attack Distribution
attack_type
normal    3078250
dos        587521
Name: count, dtype: int64

Data Types
timestamp      float64
can_id           int64
rtr              int64
dlc              int64
d0               int64
d1               int64
d2               int64
d3               int64
d4               int64
d5               int64
d6               int64
d7               int64
label            int64
attack_type        str
dtype: object

First Five Rows
      timestamp  can_id  rtr  dlc   d0   d1   d2  d3   d4   d5   d6   d7  \
0  1.478198e+09     790    0    8    5   33  104   9   33   33    0  111
1  1.478198e+09     399    0    8  254   91    0   0    0   60    0    0
2  1.478198e+09     608    0    8   25   33   34  48    8  142  109   58
3  1.478198e+09     672    0    8  100    0  154  29  151    2  189    0
4  1.478198e+09     809    0    8   64  187  127  20   17   32    0   20

   label attack_type
0      0      normal
1      0      normal
2      0      normal
3      0      normal
4      0      normal

Saved Successfully!
Location : /Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/processed/dos_processed.csv

In [54]:
fuzzy_dataset

                   0     1   2   3   4   5   6   7   8    9    10   11
0        1.478196e+09  0545   8  d8  00  00  8a  00  00   00   00    R
1        1.478196e+09  02b0   5  ff  7f  00  05  49   R  NaN  NaN  NaN
2        1.478196e+09  0002   8  00  00  00  00  00  01   07   15    R
3        1.478196e+09  0153   8  00  21  10  ff  00  ff   00   00    R
4        1.478196e+09  0130   8  19  80  00  ff  fe  7f   07   60    R
...               ...   ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...
2056933  1.478201e+09  018f   8  fe  59  00  00  00  41   00   00    R
2056934  1.478201e+09  0260   8  18  21  21  30  08  8f   6d   19    R
2056935  1.478201e+09  02a0   8  24  00  9a  1d  97  02   bd   00    R
2056936  1.478201e+09  0329   8  dc  b7  7f  14  11  20   00   14    R
2056937  1.478201e+09  0545   8  d8  00  00  8b  00  00   00   00    R

[2056938 rows x 12 columns]

In [55]:
from pathlib import Path
import pandas as pd

raw = Path("/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/Fuzzy_dataset.csv")
PROCESSED_DIR = Path("/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

rows = []

with open(raw, "r") as file:
    for line_num, line in enumerate(file, start=1):
        line = line.strip()
        if not line:
            continue

        parts = line.split(",")

        try:

            timestamp = float(parts[0])

            can_id = int(parts[1], 16)

            dlc = int(parts[2])
            payload = parts[3:-1]
            payload = [int(byte, 16) for byte in payload]
            while len(payload) < 8:
                payload.append(0)

            payload = payload[:8]
            raw_label = parts[-1].strip()

            if raw_label == "R":
                label = 0
                attack_type = "normal"

            elif raw_label == "T":
                label = 1
                attack_type = "fuzzy"

            else:
                continue

            rows.append({
                "timestamp": timestamp,
                "can_id": can_id,
                "rtr": 0,
                "dlc": dlc,
                "d0": payload[0],
                "d1": payload[1],
                "d2": payload[2],
                "d3": payload[3],
                "d4": payload[4],
                "d5": payload[5],
                "d6": payload[6],
                "d7": payload[7],
                "label": label,
                "attack_type": attack_type
            })

        except Exception as e:

            print(f"Skipping line {line_num}: {e}")

            continue
fuzzy_dataset = pd.DataFrame(rows)
output_file = PROCESSED_DIR / "fuzzy.csv"
fuzzy_dataset.to_csv(output_file, index=False)

In [57]:
rpm_dataset

         1478191030.045114  0316  8  05  22  68  09 22.1  20  00  75  R
0             1.478191e+09  018f  8  fe  3b  00  00   00  3c  00  00  R
1             1.478191e+09  0260  8  19  22  22  30   ff  8f  6e  3f  R
2             1.478191e+09  02a0  8  60  00  83  1d   96  02  bd  00  R
3             1.478191e+09  0329  8  dc  b8  7e  14   11  20  00  14  R
4             1.478191e+09  0545  8  d8  00  00  83   00  00  00  00  R
...                    ...   ... ..  ..  ..  ..  ..  ...  ..  ..  .. ..
4621696       1.478201e+09  018f  8  fe  59  00  00   00  41  00  00  R
4621697       1.478201e+09  0260  8  18  21  21  30   08  8f  6d  19  R
4621698       1.478201e+09  02a0  8  24  00  9a  1d   97  02  bd  00  R
4621699       1.478201e+09  0329  8  dc  b7  7f  14   11  20  00  14  R
4621700       1.478201e+09  0545  8  d8  00  00  8b   00  00  00  00  R

[4621701 rows x 12 columns]

In [ ]:
from pathlib import Path
import pandas as pd

raw = Path("/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/Fuzzy_dataset.csv")
PROCESSED_DIR = Path("/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

rows = []

with open(raw, "r") as file:
    for line_num, line in enumerate(file, start=1):
        line = line.strip()
        if not line:
            continue

        parts = line.split(",")

        try:

            timestamp = float(parts[0])

            can_id = int(parts[1], 16)

            dlc = int(parts[2])
            payload = parts[3:-1]
            payload = [int(byte, 16) for byte in payload]
            while len(payload) < 8:
                payload.append(0)

            payload = payload[:8]
            raw_label = parts[-1].strip()

            if raw_label == "R":
                label = 0
                attack_type = "normal"

            elif raw_label == "T":
                label = 1
                attack_type = "fuzzy"

            else:
                continue

            rows.append({
                "timestamp": timestamp,
                "can_id": can_id,
                "rtr": 0,
                "dlc": dlc,
                "d0": payload[0],
                "d1": payload[1],
                "d2": payload[2],
                "d3": payload[3],
                "d4": payload[4],
                "d5": payload[5],
                "d6": payload[6],
                "d7": payload[7],
                "label": label,
                "attack_type": attack_type
            })

        except Exception as e:

            print(f"Skipping line {line_num}: {e}")

            continue
fuzzy_dataset = pd.DataFrame(rows)
output_file = PROCESSED_DIR / "fuzzy.csv"
fuzzy_dataset.to_csv(output_file, index=False)

In [59]:
from pathlib import Path
import pandas as pd

raw = Path("/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/gear_dataset.csv")
PROCESSED_DIR = Path("/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

rows = []

with open(raw, "r") as file:
    for line_num, line in enumerate(file, start=1):
        line = line.strip()
        if not line:
            continue

        parts = line.split(",")

        try:

            timestamp = float(parts[0])

            can_id = int(parts[1], 16)

            dlc = int(parts[2])
            payload = parts[3:-1]
            payload = [int(byte, 16) for byte in payload]
            while len(payload) < 8:
                payload.append(0)

            payload = payload[:8]
            raw_label = parts[-1].strip()

            if raw_label == "R":
                label = 0
                attack_type = "normal"

            elif raw_label == "T":
                label = 1
                attack_type = "gear"

            else:
                continue

            rows.append({
                "timestamp": timestamp,
                "can_id": can_id,
                "rtr": 0,
                "dlc": dlc,
                "d0": payload[0],
                "d1": payload[1],
                "d2": payload[2],
                "d3": payload[3],
                "d4": payload[4],
                "d5": payload[5],
                "d6": payload[6],
                "d7": payload[7],
                "label": label,
                "attack_type": attack_type
            })

        except Exception as e:

            print(f"Skipping line {line_num}: {e}")

            continue
gear_dataset = pd.DataFrame(rows)
output_file = PROCESSED_DIR / "gear.csv"
gear_dataset.to_csv(output_file, index=False)

In [60]:
from pathlib import Path
import pandas as pd

raw = Path("/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/raw/rpm_dataset.csv")
PROCESSED_DIR = Path("/Users/vanshikasharma/Desktop/SecureVANET-AI/datasets/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

rows = []

with open(raw, "r") as file:
    for line_num, line in enumerate(file, start=1):
        line = line.strip()
        if not line:
            continue

        parts = line.split(",")

        try:

            timestamp = float(parts[0])

            can_id = int(parts[1], 16)

            dlc = int(parts[2])
            payload = parts[3:-1]
            payload = [int(byte, 16) for byte in payload]
            while len(payload) < 8:
                payload.append(0)

            payload = payload[:8]
            raw_label = parts[-1].strip()

            if raw_label == "R":
                label = 0
                attack_type = "normal"

            elif raw_label == "T":
                label = 1
                attack_type = "rpm"

            else:
                continue

            rows.append({
                "timestamp": timestamp,
                "can_id": can_id,
                "rtr": 0,
                "dlc": dlc,
                "d0": payload[0],
                "d1": payload[1],
                "d2": payload[2],
                "d3": payload[3],
                "d4": payload[4],
                "d5": payload[5],
                "d6": payload[6],
                "d7": payload[7],
                "label": label,
                "attack_type": attack_type
            })

        except Exception as e:

            print(f"Skipping line {line_num}: {e}")

            continue
rpm_dataset = pd.DataFrame(rows)
output_file = PROCESSED_DIR / "rpm.csv"
rpm_dataset.to_csv(output_file, index=False)